language: d

d: dmd-2.067.1

node_js:
  - "0.10"

before_script:
  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.1.5/doveralls_linux_travis"
  - chmod +x doveralls
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd client
  - npm install
  - bower install
  - cd ..

script:
  - cd client && grunt && cd .. || (cd .. && false)
  - dub test --compiler=${DC} -b unittest-cov
  - ./doveralls -t ${COVERALL_TOKEN}
