language: d

node_js:
  - "0.10"

before_script:
  - wget -q -O - "http://bit.ly/Doveralls" | bash
  - chmod +x doveralls
  - npm install -g grunt-cli
  - npm install -g bower
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - cd client
  - npm install
  - bower install
  - cd ..

script:
  - cd client && grunt && cd .. || (cd .. && false)
  - dub test --compiler=${DC} -b unittest-cov
  - ./doveralls -t ${COVERALL_TOKEN}
